对于numpy,写下在学习机器学习中,常常用到的函数.

#### 1.arange
生成具有array格式的数组.
![arange](http://upload-images.jianshu.io/upload_images/5760375-d8039b2f11d9936e.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

#### 2.linspace
生成等步长的数组,这个会在matplotlib中,作为生成数据点用到
![linspace.png](http://upload-images.jianshu.io/upload_images/5760375-3d4006295205df37.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

#### 3.random
random.randint 生成随机整数
![randint.png](http://upload-images.jianshu.io/upload_images/5760375-3dc6bda86c3d2ba0.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

random.random 生成0~1之间的浮点数
![random](http://upload-images.jianshu.io/upload_images/5760375-10efa8c5450d4305.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

random.normal 生成正态分布,默认为为(0,1)
![random.normal.png](http://upload-images.jianshu.io/upload_images/5760375-1b49e87859748958.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

#### 5.基本属性
ndim表示维度,shape表示各个维度的元素个数
shape的第一个为行,求行也可以用len()
![基本属性.png](http://upload-images.jianshu.io/upload_images/5760375-e5de9d5cd81f4320.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

#### 6.数据访问
选取数据,可以在方括号里面,输入对应的索引,也可以通过":"的方式,进行切片.
![数据访问.png](http://upload-images.jianshu.io/upload_images/5760375-4751be106fd3e23b.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)


#### 7.reshape
改变数据维度.
![reshape](http://upload-images.jianshu.io/upload_images/5760375-cd8e83afe3ac24cf.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

注意一维向量和二维数组是不同的概念.
一维向量 (10,)
二维数组(10,1) 两者维度不一样,使用concatenate时,不能进行拼接
![concatenate](http://upload-images.jianshu.io/upload_images/5760375-bfba6d3f99546e25.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

#### 8.矩阵的拼接
为了让向量和矩阵拼接,使用vstack和hstack
![vstack和hstack.png](http://upload-images.jianshu.io/upload_images/5760375-1c0e109ab6f9a873.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)


#### 9.矩阵的运算
##### a. universal functions 
矩阵 对 矩阵 对应元素进行计算
矩阵 对 数字 对原有矩阵的所有元素进行计算
![universal functions ](http://upload-images.jianshu.io/upload_images/5760375-2455dd33027b024e.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)
![universal functions](http://upload-images.jianshu.io/upload_images/5760375-a6df748e2371ad92.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

##### b. 矩阵之间的计算
![矩阵之间的计算](http://upload-images.jianshu.io/upload_images/5760375-219fc3bb555854f9.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)


#### c. 向量对矩阵的运算
![向量对矩阵的运算](http://upload-images.jianshu.io/upload_images/5760375-70885e614ee2dd50.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

### d. 聚合操作
其中往往会操作axie
记忆axis的方法 如果axis = 0 就是不要行这个维度,把行压缩掉 如果axis = 1 就是不要列这个维度,把列压缩掉

![聚合操作](http://upload-images.jianshu.io/upload_images/5760375-69b95eefec530288.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

#### 10.排序操作
最常常使用的是argsort,获得排序后的索引
![argsort](http://upload-images.jianshu.io/upload_images/5760375-0505a569262a3f65.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)


In [2]:
import numpy

In [3]:
numpy.__version__

'1.13.1'

In [5]:
import numpy as np

161 ns ± 4.15 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


### list

In [7]:
L = [i for i in range(10)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [11]:
L[5] = L

### numpy

In [23]:
nparr = np.array([i for i in range(10)])

In [26]:
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
#只能存储一种数据类型
nparr[5] = 'machine learning'

ValueError: invalid literal for int() with base 10: 'machine learning'

In [30]:
#查看array的datatype
nparr.dtype

dtype('int64')

In [31]:
#传给浮点数,也进行了截尾
nparr[5] = 3.21

In [32]:
nparr

array([0, 1, 2, 3, 4, 3, 6, 7, 8, 9])

In [33]:
#自动转换为浮点数类型
a = np.array([1,2.3,3])

In [34]:
a.dtype

dtype('float64')


### 其他创建np.array的方法

In [35]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [37]:
np.zeros((3,5),dtype = 'int')

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
np.zeros(shape = (3,5),dtype = 'int')

In [38]:
np.ones(10)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [40]:
#创建制定值的矩阵
np.full((3,5),666.)

array([[ 666.,  666.,  666.,  666.,  666.],
       [ 666.,  666.,  666.,  666.,  666.],
       [ 666.,  666.,  666.,  666.,  666.]])

### arange

In [41]:
[i for i in range(0,20,2)]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [43]:
np.arange(0,20,2)
#与range一模一样,不过step可以浮点数.

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [44]:
np.arange(0,20,0.5)

array([  0. ,   0.5,   1. ,   1.5,   2. ,   2.5,   3. ,   3.5,   4. ,
         4.5,   5. ,   5.5,   6. ,   6.5,   7. ,   7.5,   8. ,   8.5,
         9. ,   9.5,  10. ,  10.5,  11. ,  11.5,  12. ,  12.5,  13. ,
        13.5,  14. ,  14.5,  15. ,  15.5,  16. ,  16.5,  17. ,  17.5,
        18. ,  18.5,  19. ,  19.5])

### linspace

In [45]:
np.linspace(0,20,10)
#在0和20之间,等长的截取10个点,包括了0和20
#第三个参数是截取多少个数

array([  0.        ,   2.22222222,   4.44444444,   6.66666667,
         8.88888889,  11.11111111,  13.33333333,  15.55555556,
        17.77777778,  20.        ])

### random

In [57]:
np.random.randint(0,10)

2

In [58]:
np.random.randint(0,10,10)
#区间前闭后开

array([2, 5, 1, 7, 9, 8, 3, 0, 8, 6])

In [60]:
np.random.randint(0,1,10)
#区间前闭后开

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [61]:
np.random.randint(0,3,size = (3,3))

array([[1, 0, 1],
       [0, 1, 1],
       [1, 0, 2]])

In [67]:
#随机种子,让每次生成的随机数是相等的.
np.random.seed(666)
np.random.randint(0,3,size = (3,3))

array([[0, 2, 1],
       [2, 2, 2],
       [1, 2, 0]])

In [68]:
np.random.seed(666)
np.random.randint(0,3,size = (3,3))

array([[0, 2, 1],
       [2, 2, 2],
       [1, 2, 0]])

In [2]:
#生成浮点数
#random.random生成的0-1之间均匀的浮点数
import numpy as np
np.random.random(10)

array([ 0.2421323 ,  0.15476053,  0.76044462,  0.33846588,  0.13160701,
        0.02271713,  0.62418378,  0.52014167,  0.39514718,  0.12051456])

In [72]:
#生成均值为0,方差为1的浮点数
np.random.normal()

-1.7768898338073986

In [74]:
#均值为10,方差为100
np.random.normal(10,100,(3,5))

array([[ -64.95674054,  -28.480188  ,  130.08913081,  -77.82644875,
         -36.79794377],
       [ 100.6805737 ,  101.86082415,   50.18018421,   63.77026468,
           6.46425903],
       [  17.66654574,  -31.77957515,  106.71437248,  -11.32681324,
          54.07669167]])

### numpy的基本操作

In [76]:
x = np.arange(10)
X = np.arange(15).reshape(3,5)

In [77]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### 基本属性

In [83]:
x.ndim
#查看数组的维度

1

In [85]:
x.shape
#返回的各个维度的元素个数

(10,)

In [86]:
x.size
#f返回的元素个数

10

In [87]:
X.size

15

### 数据访问

In [91]:
X[(0,2)]

2

In [92]:
#最好的写法
X[0,2]

2

In [89]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [93]:
x[0:5]

array([0, 1, 2, 3, 4])

In [99]:
#双冒号后是步长,可以取负数.
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [101]:
X[0].ndim

1

In [103]:
X[0,:].ndim

1

In [106]:
X[:,0].ndim

1

In [108]:
subX = X[:2,:3]
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [109]:
subX[0,0] = 100

In [110]:
X

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [111]:
#使用了copy之后,相互就独立了
subX = X[:2,:3].copy()

In [114]:
subX[0,0]  = 0
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [115]:
X

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

### Reshape

In [116]:
x.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [117]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
## 注意一维的向量和二维的矩阵是两个概念


In [119]:
B = x.reshape(1,10)
B

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [122]:
B.ndim

2

In [128]:
#想要5行,每行多少元素不关心,用负数去代替.
x.reshape(5,-2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [129]:
x.reshape(-1,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

## 3.6 数组的合并

In [130]:
x = np.array([1,2,3])
y = np.array([3,2,1])

In [135]:
A = np.concatenate([x,y]).reshape(2,3)

In [136]:
A

array([[1, 2, 3],
       [3, 2, 1]])

In [142]:
B = np.concatenate([A,A],axis = 1)
B

array([[1, 2, 3, 1, 2, 3],
       [3, 2, 1, 3, 2, 1]])

In [147]:
z = np.array([666,666,666])
z

array([666, 666, 666])

In [148]:
np.concatenate([A,z])
#一个二维矩阵,一个一维向量,不能够拼接

ValueError: all the input arrays must have same number of dimensions

In [151]:
np.concatenate([A,z.reshape(1,-1)])

array([[  1,   2,   3],
       [  3,   2,   1],
       [666, 666, 666]])

In [152]:
A2 = np.concatenate([A,z.reshape(1,-1)])

In [154]:
np.vstack([A,z])
#V:垂直方向,stack:将数据迭在一起,可以将不同维度的数据进行堆叠

array([[  1,   2,   3],
       [  3,   2,   1],
       [666, 666, 666]])

In [157]:
B = np.full((2,2),100)
B

array([[100, 100],
       [100, 100]])

In [160]:
np.hstack([A,B])

array([[  1,   2,   3, 100, 100],
       [  3,   2,   1, 100, 100]])

In [161]:
np.hstack([A,z])

ValueError: all the input arrays must have same number of dimensions

### 分割操作

In [173]:
x = np.random.randint(0,10,10)
x

array([0, 0, 6, 6, 0, 3, 2, 9, 2, 6])

In [175]:
np.split(x,[3,7])
#将向量进行分割,分割时,左闭右开,传入的是索引

[array([0, 0, 6]), array([6, 0, 3, 2]), array([9, 2, 6])]

In [166]:
x1,x2,x3 =   np.split(x,[3,7])

In [167]:
x1

array([0, 1, 2])

In [171]:
#将向量切合成两段,分割点传入的是数组(索引)
np.split(x,[5])

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [178]:
A = np.arange(16).reshape(4,4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [182]:
np.split(A,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [186]:
np.split(A,[2],axis =1)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [187]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [184]:
np.vsplit(A,[2])
#垂直方向分割,竖线的中间分割

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [185]:
np.hsplit(A,[2])
#水平方向分割,水平线的中间分割

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [196]:
X,y = np.hsplit(A,[-1])

In [201]:
y.reshape(-1)

array([ 3,  7, 11, 15])

In [203]:
y

array([[ 3],
       [ 7],
       [11],
       [15]])

In [204]:
y[:,0]
#将矩阵转化为向量

array([ 3,  7, 11, 15])

## 3.7 numpy的矩阵运算

### universal functions

In [211]:
x = np.arange(16).reshape(4,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [212]:
x + x

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [214]:
x - x

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [215]:
x * x

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121],
       [144, 169, 196, 225]])

In [217]:
x / 10

array([[ 0. ,  0.1,  0.2,  0.3],
       [ 0.4,  0.5,  0.6,  0.7],
       [ 0.8,  0.9,  1. ,  1.1],
       [ 1.2,  1.3,  1.4,  1.5]])

In [218]:
x // 10

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 1, 1],
       [1, 1, 1, 1]])

In [219]:
x ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121],
       [144, 169, 196, 225]])

In [221]:
x % 2

array([[0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 1]])

In [222]:
1 / x

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[        inf,  1.        ,  0.5       ,  0.33333333],
       [ 0.25      ,  0.2       ,  0.16666667,  0.14285714],
       [ 0.125     ,  0.11111111,  0.1       ,  0.09090909],
       [ 0.08333333,  0.07692308,  0.07142857,  0.06666667]])

In [223]:
np.abs(x)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [224]:
np.sin(x)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021],
       [-0.53657292,  0.42016704,  0.99060736,  0.65028784]])

In [225]:
np.exp(x)
#取每个数据e次方

array([[  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
          2.00855369e+01],
       [  5.45981500e+01,   1.48413159e+02,   4.03428793e+02,
          1.09663316e+03],
       [  2.98095799e+03,   8.10308393e+03,   2.20264658e+04,
          5.98741417e+04],
       [  1.62754791e+05,   4.42413392e+05,   1.20260428e+06,
          3.26901737e+06]])

In [226]:
np.power(3,x)
#3的X次方

array([[       1,        3,        9,       27],
       [      81,      243,      729,     2187],
       [    6561,    19683,    59049,   177147],
       [  531441,  1594323,  4782969, 14348907]])

In [227]:
3**X

array([[      1,       3,       9],
       [     81,     243,     729],
       [   6561,   19683,   59049],
       [ 531441, 1594323, 4782969]])

In [233]:
np.log(x)
#以自然对数为底

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([[       -inf,  0.        ,  0.69314718,  1.09861229],
       [ 1.38629436,  1.60943791,  1.79175947,  1.94591015],
       [ 2.07944154,  2.19722458,  2.30258509,  2.39789527],
       [ 2.48490665,  2.56494936,  2.63905733,  2.7080502 ]])

### 矩阵运算

In [239]:
A = np.arange(4).reshape(2,2)
B = np.full((2,2),10)

In [241]:
A

array([[0, 1],
       [2, 3]])

In [240]:
B

array([[10, 10],
       [10, 10]])

在numpy中,运算符的定义,都是对应元素做预算,所以A*B不是真正的矩阵乘法

In [242]:
A *B

array([[ 0, 10],
       [20, 30]])

In [243]:
A / B

array([[ 0. ,  0.1],
       [ 0.2,  0.3]])

In [245]:
#矩阵的乘法..
A.dot(B)

array([[10, 10],
       [50, 50]])

In [246]:
A.T

array([[0, 2],
       [1, 3]])

### 向量和矩阵的运算

In [247]:
v = np.array([1,2])

In [248]:
A

array([[0, 1],
       [2, 3]])

In [249]:
#数学中是没有意义的,但是在numpy中,自动将低维和高维相加
v + A

array([[1, 3],
       [3, 5]])

In [255]:
np.vstack([v] * A.shape[0])
#就是将向量迭两次

array([[1, 2],
       [1, 2]])

In [258]:
np.vstack([v]*2)

array([[1, 2],
       [1, 2]])

In [259]:
A.shape[0]

2

In [263]:
np.tile(v,(2,1))
#(2,1)的含义是,在行向量堆叠2次,列向量堆叠1次.

array([[1, 2],
       [1, 2]])

In [264]:
#向量与矩阵之间相乘
v.dot(A)

array([4, 7])

In [265]:
A.dot(v)
#np自动将行向量转化为列向量`

array([2, 8])

### 矩阵的逆
设A是数域上的一个n阶方阵，若在相同数域上存在另一个n阶矩阵B，使得： AB=BA=E。 则我们称B是A的逆矩阵，而A则被称为可逆矩阵。注：E为单位矩阵

In [266]:
A

array([[0, 1],
       [2, 3]])

In [267]:
np.linalg.inv(A)
# Linear algebra 线性代数 inv逆矩阵

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [269]:
invA = np.linalg.inv(A)

In [270]:
A.dot(invA)

array([[ 1.,  0.],
       [ 0.,  1.]])

In [271]:
invA.dot(A)

array([[ 1.,  0.],
       [ 0.,  1.]])

In [274]:
X = np.arange(16).reshape(2,-1)
X

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [276]:
np.linalg.pinv(X)
#求伪逆矩阵. 对于非方阵而言.

array([[ -1.35416667e-01,   5.20833333e-02],
       [ -1.01190476e-01,   4.16666667e-02],
       [ -6.69642857e-02,   3.12500000e-02],
       [ -3.27380952e-02,   2.08333333e-02],
       [  1.48809524e-03,   1.04166667e-02],
       [  3.57142857e-02,  -1.04083409e-17],
       [  6.99404762e-02,  -1.04166667e-02],
       [  1.04166667e-01,  -2.08333333e-02]])

In [282]:
a= np.linalg.pinv(X)

In [284]:
X.dot(a)

array([[  1.00000000e+00,  -2.49800181e-16],
       [  0.00000000e+00,   1.00000000e+00]])

### 3.8聚合操作

In [286]:
L = np.random.random(100)

In [287]:
sum(L)

50.292623589299325

In [289]:
np.sum(L)

50.292623589299296

In [290]:
L.max()

0.99491380718445055

In [291]:
np.max(L)
#推荐使用np方式

0.99491380718445055

In [294]:
X = np.arange(16).reshape(4,4)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

记忆axis的方法
如果axis = 0  就是不要行这个维度,把行压缩掉
如果axis = 1 就是不要列这个维度,把列压缩掉

In [295]:
np.sum(X,axis = 0)

array([24, 28, 32, 36])

In [296]:
np.sum(X,axis = 1)

array([ 6, 22, 38, 54])

In [298]:
#prod 相乘矩阵中所有的元素
np.prod(X +1)

20922789888000

In [299]:
np.mean(X)

7.5

In [300]:
np.median(X)
#中位数`

7.5

In [304]:
np.percentile(X,q= 50)
#在X中 50%的数字小于 7.5
#求百分位

7.5

In [305]:
#求方差
np.var(X)

21.25

In [306]:
#求标准差
np.std(X)

4.6097722286464435

## 3.9 arg运算

### 索引

In [320]:
x  = np.random.normal(0,1,1000000)

In [321]:
x.std()

0.99952331703975961

In [322]:
x.mean()

0.0011786582037964736

In [324]:
np.min(x)

-4.7721092921214012

In [327]:
np.argmin(x)
#得到最小值的索引

136919

### 排序与使用索引

In [329]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [331]:
#对x进行乱序处理,注意用了np后,也改变了x的值
np.random.shuffle(x)
x

array([ 6,  7, 10,  8,  3, 15, 11, 13,  1,  2, 12, 14,  5,  4,  9,  0])

In [336]:
x.sort()
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [340]:
X = np.random.randint(0,9,(4,4))
X

array([[6, 6, 3, 6],
       [4, 4, 5, 4],
       [8, 6, 4, 5],
       [0, 1, 0, 1]])

In [341]:
np.sort(X)
#默认axis = 1 沿着列方向排序

array([[3, 6, 6, 6],
       [4, 4, 4, 5],
       [4, 5, 6, 8],
       [0, 0, 1, 1]])

In [343]:
np.sort(X,axis = 0)

array([[0, 1, 0, 1],
       [4, 4, 3, 4],
       [6, 6, 4, 5],
       [8, 6, 5, 6]])

In [344]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [346]:
np.random.shuffle(x)
x

array([ 7, 10,  0,  2, 13,  8,  4,  3, 11, 15,  1, 14, 12,  9,  6,  5])

In [347]:
np.argsort(x)
#按照值的大小,进行排序,用索引表示

array([ 2, 10,  3,  7,  6, 15, 14,  0,  5, 13,  1,  8, 12,  4, 11,  9])

In [348]:
#找到排序的标定点
np.partition(x,3)
#3前的数字比3小,后面的数字比3大

array([ 0,  1,  2,  3,  4,  5,  8, 10, 11, 15, 13, 14, 12,  9,  6,  7])

In [349]:
np.argpartition(x,3)

array([ 2, 10,  3,  7,  6, 15,  5,  1,  8,  9,  4, 11, 12, 13, 14,  0])

### Fancy indexing

In [352]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [355]:
x[[3,4,0]]

array([3, 4, 0])

In [358]:
# 索引是二维数组,结果也成了二维数据
ind = np.array([[0,2],
                [1,3]])

In [359]:
x[ind]

array([[0, 2],
       [1, 3]])

In [367]:
X = x.reshape(4,-1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [362]:
row = np.array([1,2])
col = np.array([1,2])

In [366]:
X[row,col]

array([ 5, 10])

In [370]:
col = [True,False,True,False]

In [373]:
X[1:3,col]

array([[ 4,  6],
       [ 8, 10]])

### numpy中 array的比较

In [374]:
x < 3

array([ True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False], dtype=bool)

In [375]:
x[x<3]

array([0, 1, 2])

In [376]:
x <= 3

array([ True,  True,  True,  True, False, False, False, False, False,
       False, False, False, False, False, False, False], dtype=bool)

In [377]:
np.sum(x <= 3)
#true为1 false为0

4

In [378]:
np.count_nonzero(x <= 3)

4

In [380]:
np.any(x == 0)

True

In [382]:
np.any(x < 0)
#any:至少一个

False

In [384]:
#all 全部
np.all(x >0)

False