In [1]:
import numpy as np
from sklearn import datasets

In [2]:
iris = datasets.load_iris()

In [3]:
X = iris.data
y = iris.target

In [4]:
X[:10]

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.4,  3.9,  1.7,  0.4],
       [ 4.6,  3.4,  1.4,  0.3],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 4.4,  2.9,  1.4,  0.2],
       [ 4.9,  3.1,  1.5,  0.1]])

In [5]:
#先进行train test split
from sklearn.model_selection import train_test_split

In [6]:
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state = 666)

### sklearn 中的stranderdscaler

In [7]:
#加载preprocessing预处理包中的StandardScaler
from sklearn.preprocessing import StandardScaler

In [8]:
standardScaler = StandardScaler()

In [9]:
standardScaler.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [10]:
standardScaler.mean_
#standardScaler.mean_是用户传给的数据,计算出的变量,所以有下划线

array([ 5.825     ,  3.08839286,  3.68660714,  1.16339286])

In [11]:
#方差,描述数据的分布范围
standardScaler.scale_

array([ 0.80239597,  0.44676327,  1.75715352,  0.75663677])

In [12]:
X_train =  standardScaler.transform(X_train)

In [13]:
X_test_standard =  standardScaler.transform(X_test)

In [14]:
# 对归一化后的数据进行KNN分类

In [15]:
from sklearn.neighbors import KNeighborsClassifier

In [18]:
knn_clf = KNeighborsClassifier(n_neighbors=3)

In [19]:
knn_clf.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=3, p=2,
           weights='uniform')

In [20]:
knn_clf.score(X_test_standard,y_test)

0.97368421052631582

In [21]:
#没有传入归一化处理
knn_clf.score(X_test,y_test)

0.34210526315789475